version: '3'
services:
  jenkins:
    image: jenkins/jenkins 
    ports:
        - 8080:8080
        - 50000:50000
    container_name: jenkins 
    volumes:
        - /g2284230660101/jenkins/jenkins_home:/var/jenkins_home 
    networks:
        - net
networks:
  net: 